# Generated by Django 3.0.7 on 2020-06-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendar_schedule.UserData'),
        ),
    ]
